version: "3"

services:
  backend:
    container_name: jumia-backend
    build: ./jumia-interview-backend/
    ports:
      - "8481:8080"
    restart: always
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:sqlite:app/db/sample.db
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
    networks:
      - internal
  frontend:
    container_name: jumia-frontend
    build: ./jumia-interview-frontend/
    links:
      - "backend"
    depends_on:
      - "backend"
    ports:
      - "8480:80"
    networks:
      - external
      - internal
networks:
  external:
    driver: bridge
  internal:
    driver: bridge
